# Generated by Django 4.2.3 on 2023-07-21 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('doj', models.DateField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, default='', upload_to='images/')),
                ('dob', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Working', 'Working'), ('Not Working', 'Not Working'), ('Under Evaluation', 'Under Evaluation'), ('Selection In Process', 'Selection In Process'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='', max_length=20)),
                ('attested', models.ImageField(blank=True, default='', upload_to='attested/')),
                ('c4', models.ImageField(blank=True, default='', upload_to='c4/')),
                ('sign_off', models.ImageField(blank=True, default='', upload_to='sign_off/')),
                ('acc_num', models.CharField(blank=True, default='', max_length=30)),
                ('ifsc', models.CharField(blank=True, default='', max_length=30)),
                ('aadhar', models.ImageField(blank=True, default='', upload_to='aadhar/')),
                ('aadhar_attested', models.ImageField(blank=True, default='', upload_to='aadhar_attested/')),
                ('designation', models.CharField(blank=True, default='', max_length=20)),
                ('program_enroll', models.CharField(blank=True, default='', max_length=30)),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('c4_date', models.DateField(blank=True, null=True)),
                ('c4_exp', models.IntegerField(blank=True, default=90)),
                ('city_reg', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hr.citymodel')),
            ],
        ),
    ]
