# Generated by Django 4.2.3 on 2023-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_registermodel_c4_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='c4_exp',
            field=models.CharField(blank=True, default='90', max_length=100),
        ),
    ]
