# Generated by Django 4.2.3 on 2023-07-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_registermodel_c4_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='mobile',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
