# Generated by Django 4.2.3 on 2023-07-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_registermodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='c4_exp',
            field=models.IntegerField(blank=True, default='90'),
        ),
    ]
