# Generated by Django 4.2.3 on 2023-08-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_registermodel_c4_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
