# Generated by Django 4.2.3 on 2023-08-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_registermodel_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='attested',
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='c4_exp',
            field=models.IntegerField(blank=True, default='365'),
        ),
    ]
