# Generated by Django 4.2.3 on 2023-08-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_registermodel_attested_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='aadhar_attested',
            new_name='aadharAttested',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='acc_num',
            new_name='accNnum',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='c4_date',
            new_name='c4Date',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='c4_exp',
            new_name='c4Exp',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='city_reg',
            new_name='cityReg',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='program_enroll',
            new_name='programEnroll',
        ),
    ]
