# Generated by Django 4.2.3 on 2023-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_rename_aadhar_attested_registermodel_aadharattested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='aadhar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='aadhar/'),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='accNnum',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='c4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='c4/'),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='code',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='ifsc',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='programEnroll',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='sign_off',
            field=models.ImageField(blank=True, default='', null=True, upload_to='sign_off/'),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Working', 'Working'), ('Not Working', 'Not Working'), ('Under Evaluation', 'Under Evaluation'), ('Selection In Process', 'Selection In Process'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='', max_length=20, null=True),
        ),
    ]
