# Generated by Django 4.2.3 on 2023-08-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_registermodel_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='c4Exp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
