# Generated by Django 4.2.3 on 2023-08-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_alter_registermodel_c4exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='dol',
            field=models.DateField(blank=True, null=True),
        ),
    ]
